### ISSUE TITLE
CLI gets stuck when no file is used as parameter

### ISSUE THREAD

**Issue by MartinMuzatko** [hjson/hjson-go#12]
When using `hjson -j` without a file, hjson gets stuck.
An exit code 1 would be preferable then.
I stumbled across this, when I wanted to write a systemctl system service that parses a hjson file, but the environment variable was not set (as it the defualt in system services) and then the script was stuck there forever. Only after inspecting the tree with `htop` I could see that hjson is executed forever.

**Comment by philippgille** [comment]
It looks like `hjson -j` without a file parameter uses the standard input as input, see https://github.com/hjson/hjson-go/blob/c307adb935d515b8032fd94ca4fc253b3842deeb/hjson-cli/main.go#L57.

So exiting with 1 would break this feature.

Maybe the feature should be changed to take standard input only when something like `-` or `--` is given as parameter? Would be a breaking change though. Maybe something for v4.0.0?

**Comment by trobro** [comment]
Reading stdin when no file was specified is a common behavior in command line tools, so that text can be piped to them. See e.g. the tool *sed*.
