### ISSUE TITLE
Includes trailing comma character in unquoted list items

### ISSUE THREAD

**Issue by CameronNemo** [hjson/hjson-go#18]
Given the following hjson:

```
{
    foo: [
        bar,
        baz
    ]
}
```

I would expect the output to be:

```
{
  "foo": [
    "bar",
    "baz"
  ]
}
```

But instead I get:

```
{
  "foo": [
    "bar,",
    "baz"
  ]
}
```

To get the expected output, I need to quote the list item or not use a trailing comma in lists.

**Comment by trobro** [comment]
In Hjson that is the expected behavior. According to the syntax definition for quoteless strings, all characters until the line feed are considered part of the string:

https://hjson.github.io/syntax.html
