### ISSUE TITLE
Integers are unmarshalled into float64

### ISSUE THREAD

**Issue by chmike** [hjson/hjson-go#2]
Current implementation decode integers into float64 values.
This introduces a limitation in the integer values magnitude that can be handled by the hjson library.

**Comment by chmike** [comment]
In Javascript integers are encoded in float64. So the JSON format implies the magnitude limitation. A JSON encoded string with integer values that can't be encoded in float64 won't be readable by JavaScript. 
Encoding any numeric values into float64 is thus the right choice.

**Comment by laktak** [comment]
@chmike thanks for the comment. If you prefer a different implementation you could always use hjson-go to parse and convert the Hjson data and then use that with your preferred JSON library.
