### ISSUE TITLE
Unmashal to struct

### ISSUE THREAD

**Issue by ddkwork** [hjson/hjson-go#29]
How to unmashal to struct not map string interface

**Comment by trobro** [comment]
One way is to marshal into JSON as an intermediate step.

**Comment by trobro** [comment]
// read Hjson
    var dat map[string]interface{}
    hjson.Unmarshal(sampleText, &dat)

    // convert to JSON
    b, _ := json.Marshal(dat)

    // unmarshal
    var sample Sample
    json.Unmarshal(b, &sample)

**Comment by bronze1man** [comment]
I have comfired that this library is not work just like json.Unmarshal
```
package main

import (
	"github.com/hjson/hjson-go"
	"fmt"
)

func main(){
	type Node struct{
		F string
	}
	var obj Node
	err := hjson.Unmarshal([]byte(`
F: good
`),&obj)
	if err!=nil{
		panic(err)
	}
	fmt.Println(obj.F)
}
```
