### ISSUE TITLE
support marshal net.ParseIP(`127.0.0.1`) to 127.0.0.1

### ISSUE THREAD

**Issue by bronze1man** [hjson/hjson-go#34]
support marshal net.ParseIP(`127.0.0.1`) to 127.0.0.1

current result:
```
[
  0
  0
  0
  0
  0
  0
  0
  0
  0
  0
  255
  255
  127
  0
  0
  1
]
```

support encoding.TextMarshaler should fix this bug.

**Comment by trobro** [comment]
The current result is consistent with doing `fmt.Printf` of such an object:

    net.IP{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff, 0xff, 0x7f, 0x0, 0x0, 0x1}

**Comment by bronze1man** [comment]
The current result is not consistent with json.Marshal of such an object.

**Comment by trobro** [comment]
I see, it would have been better to be consistent with json.Marshal. Unfortunately changing that now would be a breaking change, it could cause problems for people who depend on the current behavior of Hjson. Let's leave this issue open, maybe we can do a 4.0 release in the future with breaking changes like this one.
