### ISSUE TITLE
can not unmarshal obj from marshal result with string "0\r'"

### ISSUE THREAD

**Issue by bronze1man** [hjson/hjson-go#37]
test code:
```go
func TestEncodeMarshalAndUnmarshal(t *testing.T) {
	type t_obj struct{
		F string
	}
	const testS = "0\r'"
	input := t_obj{
		F: "0\r'",
	}
	buf, err := Marshal(input)
	if err != nil {
		t.Fatal(err)
	}
	var obj2 t_obj
	err = Unmarshal(buf,&obj2)
	if err != nil {
		t.Fatal(err)
	}
	if obj2.F!=testS{
		t.Error("fail ["+hex.Dump([]byte(obj2.F))+`]`)
	}
}
```

**Comment by bronze1man** [comment]
get error `Bad string containing newline at line 3,0 >>> }`

**Comment by trobro** [comment]
According to this documentation Hjson will always use `\n` for line feed in multiline strings:

https://hjson.github.io/syntax.html

So `\r\n` will be changed into `\n`, the original string will be altered. But it seems like a mistake that `\r` is always removed even if there is no `\n` after it. Would probably be better to change `\r` into `\n`. I'll do that in hjson-go version 4.

**Comment by trobro** [comment]
I thought some more on this, came to the conclusion that the Marshal function should never alter strings. If a string contains `\r` then the Marshal function should output a quoted string, not a multiline string. The text in the syntax documentation about Hjson always using `\n` for line feed in multiline strings should only affect the Unmarshal function. The Marshal function has always used `EncoderOptions.Eol` for line feed in multiline strings in the output Hjson, and should keep doing that.
