### ISSUE TITLE
module path must match major version

### ISSUE THREAD

**Issue by iangudger** [hjson/hjson-go#39]
When fetching this package, I get the following error:

```
go get github.com/hjson/hjson-go@v3.2.0
go: github.com/hjson/hjson-go@v3.2.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/hjson/hjson-go/v3")
```

It looks like that, according to https://github.com/golang/go/issues/35732, this can be fixed by modifying the path here:
https://github.com/hjson/hjson-go/blob/e669f6bde0de3f1f87961258f47f7a78bd16bb60/go.mod#L1
...to `github.com/hjson/hjson-go/v3`.

**Comment by trobro** [comment]
Thanks for the suggestion! It was a mistake of me to add the go.mod file, I only did it to get automatic tests running again. Changing the path for the existing version 3 would be a breaking change, everyone would need to change the import path. So instead I'm planning to remove the go.mod file from version 3 and do a version 4 release with a proper go.mod file, where the module path ends with /4. Just wanted to find the time for some code changes too...

**Comment by trobro** [comment]
v4.0.0 has been released, closing this.
