### ISSUE TITLE
"Unmarshal to structs" example in readme doesn't work

### ISSUE THREAD

**Issue by yujiri8** [hjson/hjson-go#57]
The structs are left as their zero values. The errors are ignored in the example code. If I log the errors, it says `reflect.Set: value of type map[string]interface {} is not assignable to type main.Sample`.

my Go version: `go1.20.7 linux/amd64`

**Comment by trobro** [comment]
You need to use version 4 or later of hjson-go in order to unmarshal to structs. Make sure you import hjson-go like this:

```go
import "github.com/hjson/hjson-go/v4"
```

**Comment by yujiri8** [comment]
Sorry, my mistake.
