### ISSUE TITLE
Easy way to unmarshal to struct without assertions?

### ISSUE THREAD

**Issue by isavcic** [hjson/hjson-go#6]
Hello,

Sorry if the answer is too obvious as I'm a beginner in Go, but is there an easy way to do [this](https://play.golang.org/p/WYpQBHgby3) with hjson and hjson-go without all the assertions as presented in the doc?

Thanks

**Comment by laktak** [comment]
I'm not sure what you are asking. Did you see the [sample usage](https://github.com/hjson/hjson-go#usage)?

**Comment by isavcic** [comment]
I did, and it's using on-the-fly assertions because it can only unmarshal to an []interface{}? Is there an option to unmarshal to a proper struct immediately, like json std lib does?

**Comment by laktak** [comment]
I've added a sample to the readme. Let me know if this helps.

**Comment by isavcic** [comment]
I've actually written a function for this already, to convert binary hjson to binary json on which you could use json methods on, but it looked like an overkill:
```go
func hjson_to_json(hjson_data []byte) []byte {

        var data interface{}

        if err := hjson.Unmarshal(hjson_data, &data); err != nil {
                panic(err)
        } else if json_data, err := json.Marshal(data); err != nil {
                panic(err)
        } else {
                return json_data
        }
}
```
I guess it's the best approach, so thanks for the feedback!
