### ISSUE TITLE
Docs: null behavior with *string

### ISSUE THREAD

**Issue by kevmurray** [hjson/hjson-go#62]
Minor documentation inconsistency?

Readme:
> String pointer destinations are treated the same as string destinations, so you cannot set a string pointer to nil by writing null in an Hjson file. Writing null in an Hjson file would result in the string "null" being stored in the destination string pointer.

4.4.0 Release notes
> Slightly changed behavior for unmarshalling "null" into a string destination: if the value is "null" without quotes and the destination is a pointer then the pointer is set to nil instead of a pointer to the string "null", even if the destination is a pointer to a string or a type that implements UnmarshalText().

**Comment by trobro** [comment]
Thanks, fixed on the master branch.
