### ISSUE TITLE
Unicode escape in encoder

### ISSUE THREAD

**Issue by trobro** [hjson/hjson-go#8]
https://github.com/hjson/hjson-go/blob/ce720c650e17e3aab31e06e9ca2e402677935d72/encode.go#L85

Shouldn't a be used as input instead of c, since c must be nil?

**Comment by trobro** [comment]
And I think `a` should be converted to a rune first, using `utf8.DecodeRune()`.

**Comment by laktak** [comment]
Thanks! I've fixed it and added a test case - can you verify if it works for you?

**Comment by trobro** [comment]
It works, thanks!
